### ISSUE TITLE
ไม่มี PserverN.py ?

### ISSUE THREAD

**Issue by sctnightcore** [syntaxp/PserverN#3]
ว่าแต่จะเปิด src ของส่วน PserverN.exe ไหม ?
ขอบคุณครับ :)

**Comment by syntaxp** [comment]
[PserverN.py](https://github.com/syntaxp/PserverN/blob/master/PserverN.py)
ผมไม่แน่ใจว่าถ้าเครื่องอื่นรัน main แบบ src หลักจะต้อง ดาวโหลด PIP ด้วยไหม เปิดให้แล้วครับ
